### ISSUE TITLE
Parsing of cookie header should not fail when other cookies have been sent

### ISSUE THREAD

**Issue by timotgl** [josecardozo/hapi-auth-cookie-jwt#3]
Either the documentation should mention that the cookie header can only contain exactly *one* cookie that is interpreted as access_token, or, after doing `var authorization = request.headers.cookie;` the following code should look for a specific cookie.

**Comment by jcastets** [comment]
Hi, @josecardozo I had the same problem, so I had to fix it, making my first "contribution" to the open source world. I'm not sure I'm doing it well but here is my pull request I you mind reviewing it, I would be grateful
https://github.com/josecardozo/hapi-auth-cookie-jwt/pull/4

Thank you
